-- HarmonyBot Database Schema
-- MySQL Script generated by MySQL Workbench
-- Wed Feb 22 11:26:19 2023
-- Model: HarmonyBotSchema    Version: 1.2
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HarmonyBot
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `HarmonyBot` ;

-- -----------------------------------------------------
-- Schema HarmonyBot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HarmonyBot` DEFAULT CHARACTER SET utf8 ;
USE `HarmonyBot` ;


-- -----------------------------------------------------
-- Table `HarmonyBot`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HarmonyBot`.`Role` (
  `RoleID` INT NOT NULL,
  `RoleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RoleID`),
  UNIQUE INDEX `RoleID_UNIQUE` (`RoleID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HarmonyBot`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HarmonyBot`.`Status` (
  `StatusID` INT NOT NULL,
  `StatusName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`StatusID`),
  UNIQUE INDEX `StatusID_UNIQUE` (`StatusID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HarmonyBot`.`Commands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HarmonyBot`.`Commands` (
  `CommandID` INT NOT NULL AUTO_INCREMENT,
  `CommandInput` VARCHAR(25) NOT NULL,
  `CommandAction` VARCHAR(255) NULL,
  `CommandOutput` VARCHAR(255) NULL,
  `CommandMinRoleID` INT NOT NULL,
  PRIMARY KEY (`CommandID`),
  UNIQUE INDEX `CommandID_UNIQUE` (`CommandID` ASC) VISIBLE,
  UNIQUE INDEX `CommandInput_UNIQUE` (`CommandInput` ASC) VISIBLE,
  INDEX `fk_Commands_Role1_idx` (`CommandMinRoleID` ASC) VISIBLE,
  CONSTRAINT `fk_Commands_Role1`
    FOREIGN KEY (`CommandMinRoleID`)
    REFERENCES `HarmonyBot`.`Role` (`RoleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HarmonyBot`.`ModWords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HarmonyBot`.`ModWords` (
  `ModWordsID` INT NOT NULL AUTO_INCREMENT,
  `BadWords` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ModWordsID`),
  UNIQUE INDEX `ModWordsID_UNIQUE` (`ModWordsID` ASC) VISIBLE,
  UNIQUE INDEX `BadWords_UNIQUE` (`BadWords` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HarmonyBot`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HarmonyBot`.`User` (
  `UserName` VARCHAR(45) NOT NULL,
  `UserTag` VARCHAR(4) NOT NULL,
  `UserStatusID` INT NOT NULL,
  `UserRoleID` INT NOT NULL,
  `UserNumStrikes` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`UserName`, `UserTag`),
  INDEX `fk_User_Status1_idx` (`UserStatusID` ASC) VISIBLE,
  INDEX `fk_User_Role1_idx` (`UserRoleID` ASC) VISIBLE,
  CONSTRAINT `fk_User_Status1`
    FOREIGN KEY (`UserStatusID`)
    REFERENCES `HarmonyBot`.`Status` (`StatusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Role1`
    FOREIGN KEY (`UserRoleID`)
    REFERENCES `HarmonyBot`.`Role` (`RoleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HarmonyBot`.`ModLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HarmonyBot`.`ModLog` (
  `idModLog` INT NOT NULL AUTO_INCREMENT,
  `ModdedUserName` VARCHAR(45) NOT NULL,
  `ModdedUserTag` VARCHAR(4) NOT NULL,
  `ModLogWordsID` INT NOT NULL,
  `UserMessage` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idModLog`),
  UNIQUE INDEX `idModLog_UNIQUE` (`idModLog` ASC) VISIBLE,
  INDEX `fk_ModLog_ModWords1_idx` (`ModLogWordsID` ASC) VISIBLE,
  INDEX `fk_ModLog_User1_idx` (`ModdedUserName` ASC, `ModdedUserTag` ASC) VISIBLE,
  CONSTRAINT `fk_ModLog_ModWords1`
    FOREIGN KEY (`ModLogWordsID`)
    REFERENCES `HarmonyBot`.`ModWords` (`ModWordsID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ModLog_User1`
    FOREIGN KEY (`ModdedUserName` , `ModdedUserTag`)
    REFERENCES `HarmonyBot`.`User` (`UserName` , `UserTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
